# Generated by Django 5.2.8 on 2025-11-22 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_product_desc_remove_product_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='product',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
